import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { StateContextProvider } from '@/context/StateContext'
import '@/styles/globals.css'
import "../components/Dashboard/Reservaciones/styles/sweet-alert-custom.css"
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return (<StateContextProvider>
    <Head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Descubre el encanto de Mérida en nuestra exclusiva Casa Boutique, donde la historia se fusiona con la elegancia contemporánea para ofrecerte una experiencia única. ¡Haz de Casa Itzimná tu estancia en esta mágica ciudad! Déjate conquistar por la decoración, la atención de nuestro equipo, la gastronomía local y el encanto de Mérida a través de las experiencias únicas y cautivadoras que te ofrecemos en Casa Itzimná Boutique. Conoce la comodidad de cada rincón impregnado con el encanto de Mérida y lo contemporáneo. La Casa Boutique ha sido diseñada con el fin de ofrecer un refugio de lujo y bienestar. Descubre la calidez y elegancia de nuestros espacios. Sofisticación y bienestar sin igual, pensamos y cuidamos cada detalle de manera cuidadosa para envolverte en una sensación de elegancia y satisfacción. Permítenos transportarte a un mundo de deleite y relajación para ofrecerte un verdadero oasis de lujo y confort. La hospitalidad excepcional y nuestros servicios exclusivos te esperan para hacer de tu estancia una experiencia verdaderamente única y exquisita. Nuestra excepcional hospitalidad es lo que consideramos un verdadero arte. Ubicada en el corazón de la antigua Colonia de Itzimná, se encuentra nuestra casona de estilo colonial construida en 1961, convirtiéndola en un verdadero tesoro histórico que ha sido hogar de familias locales y testigo de la evolución de Mérida. Hoy, restaurada con esmero y delicadeza, combina la elegancia de antaño con servicios contemporáneos, ofreciendo a nuestros huéspedes una experiencia única y llena de encanto colonial. Nuestra misión es preservar y compartir la rica historia y encanto colonial de nuestra casona construida en 1961. A través de una meticulosa restauración y la incorporación de servicios contemporáneos, brindamos a nuestros huéspedes una experiencia única, llena de comodidad y autenticidad. Nos esforzamos por ser un oasis de lujo y bienestar, donde cada rincón evoca la esencia de Mérida y su pasado prehispánico. Déjate cautivar por nuestros sabores únicos y deleita tus sentidos con la gastronomía excepcional que ofrecemos, inspirados en la cocina yucateca." />
      <meta name="author" content="Casa Itzimná Boutique" />
      <meta property="og:title" content="Casa Itzimná Boutique" />
      <meta property="og:description" content="Descubre el encanto de Mérida en nuestra exclusiva Casa Boutique, donde la historia se fusiona con la elegancia contemporánea para ofrecerte una experiencia única. ¡Haz de Casa Itzimná tu estancia en esta mágica ciudad! Déjate conquistar por la decoración, la atención de nuestro equipo, la gastronomía local y el encanto de Mérida a través de las experiencias únicas y cautivadoras que te ofrecemos en Casa Itzimná Boutique. Conoce la comodidad de cada rincón impregnado con el encanto de Mérida y lo contemporáneo. La Casa Boutique ha sido diseñada con el fin de ofrecer un refugio de lujo y bienestar. Descubre la calidez y elegancia de nuestros espacios. Sofisticación y bienestar sin igual, pensamos y cuidamos cada detalle de manera cuidadosa para envolverte en una sensación de elegancia y satisfacción. Permítenos transportarte a un mundo de deleite y relajación para ofrecerte un verdadero oasis de lujo y confort. La hospitalidad excepcional y nuestros servicios exclusivos te esperan para hacer de tu estancia una experiencia verdaderamente única y exquisita. Nuestra excepcional hospitalidad es lo que consideramos un verdadero arte. Ubicada en el corazón de la antigua Colonia de Itzimná, se encuentra nuestra casona de estilo colonial construida en 1961, convirtiéndola en un verdadero tesoro histórico que ha sido hogar de familias locales y testigo de la evolución de Mérida. Hoy, restaurada con esmero y delicadeza, combina la elegancia de antaño con servicios contemporáneos, ofreciendo a nuestros huéspedes una experiencia única y llena de encanto colonial. Nuestra misión es preservar y compartir la rica historia y encanto colonial de nuestra casona construida en 1961. A través de una meticulosa restauración y la incorporación de servicios contemporáneos, brindamos a nuestros huéspedes una experiencia única, llena de comodidad y autenticidad. Nos esforzamos por ser un oasis de lujo y bienestar, donde cada rincón evoca la esencia de Mérida y su pasado prehispánico. Déjate cautivar por nuestros sabores únicos y deleita tus sentidos con la gastronomía excepcional que ofrecemos, inspirados en la cocina yucateca." />
      <meta property="og:image" content="/og.jpg" />
      <meta property="og:url" content="https://casaitzimnaboutique.com" />
      <meta property="og:type" content="website" />
      <meta name="twitter:title" content="Casa Itzimná Boutique" />
      <meta name="twitter:description" content="Descubre el encanto de Mérida en nuestra exclusiva Casa Boutique, donde la historia se fusiona con la elegancia contemporánea para ofrecerte una experiencia única. ¡Haz de Casa Itzimná tu estancia en esta mágica ciudad! Déjate conquistar por la decoración, la atención de nuestro equipo, la gastronomía local y el encanto de Mérida a través de las experiencias únicas y cautivadoras que te ofrecemos en Casa Itzimná Boutique. Conoce la comodidad de cada rincón impregnado con el encanto de Mérida y lo contemporáneo. La Casa Boutique ha sido diseñada con el fin de ofrecer un refugio de lujo y bienestar. Descubre la calidez y elegancia de nuestros espacios. Sofisticación y bienestar sin igual, pensamos y cuidamos cada detalle de manera cuidadosa para envolverte en una sensación de elegancia y satisfacción. Permítenos transportarte a un mundo de deleite y relajación para ofrecerte un verdadero oasis de lujo y confort. La hospitalidad excepcional y nuestros servicios exclusivos te esperan para hacer de tu estancia una experiencia verdaderamente única y exquisita. Nuestra excepcional hospitalidad es lo que consideramos un verdadero arte. Ubicada en el corazón de la antigua Colonia de Itzimná, se encuentra nuestra casona de estilo colonial construida en 1961, convirtiéndola en un verdadero tesoro histórico que ha sido hogar de familias locales y testigo de la evolución de Mérida. Hoy, restaurada con esmero y delicadeza, combina la elegancia de antaño con servicios contemporáneos, ofreciendo a nuestros huéspedes una experiencia única y llena de encanto colonial. Nuestra misión es preservar y compartir la rica historia y encanto colonial de nuestra casona construida en 1961. A través de una meticulosa restauración y la incorporación de servicios contemporáneos, brindamos a nuestros huéspedes una experiencia única, llena de comodidad y autenticidad. Nos esforzamos por ser un oasis de lujo y bienestar, donde cada rincón evoca la esencia de Mérida y su pasado prehispánico. Déjate cautivar por nuestros sabores únicos y deleita tus sentidos con la gastronomía excepcional que ofrecemos, inspirados en la cocina yucateca." />
      <meta name="twitter:image" content="/twitter.jpg" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta property="og:site_name" content="Casa Itzimná Boutique" />

      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600&display=swap" rel="stylesheet" />
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <link rel="apple-touch-icon" href="/apple-touch-icon.png"  />
    </Head>
    <Navbar />
    <Component {...pageProps} />
    <Footer />
  </StateContextProvider>
  )
}
